config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'
    }  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :dairies
  root to: 'dairies#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dairy.rb
class Dairy < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/dairies_controller.rb
class DairiesController < ApplicationController
  before_action :set_dairy, only: [:show, :edit, :update, :destroy]

  # GET /dairies
  # GET /dairies.json
  def home
  end

  def index
    @dairies = Dairy.all
  end

  # GET /dairies/1
  # GET /dairies/1.json
  def show
  end

  # GET /dairies/new
  def new
    @dairy = Dairy.new
  end

  # GET /dairies/1/edit
  def edit
  end

  # POST /dairies
  # POST /dairi@es.json
  def create
    @dairy = Dairy.new(dairy_params)

    respond_to do |format|
      if @dairy.save
        format.html { redirect_to @dairy, notice: 'Dairy was successfully created.' }
        format.json { render :show, status: :created, location: @dairy }
      else
        format.html { render :new }
        format.json { render json: @dairy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dairies/1
  # PATCH/PUT /dairies/1.json
  def update
    respond_to do |format|
      if @dairy.update(dairy_params)
        format.html { redirect_to @dairy, notice: 'Dairy was successfully updated.' }
        format.json { render :show, status: :ok, location: @dairy }
      else
        format.html { render :edit }
        format.json { render json: @dairy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dairies/1
  # DELETE /dairies/1.json
  def destroy
    @dairy.destroy
    respond_to do |format|
      format.html { redirect_to dairies_url, notice: 'Dairy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dairy
      @dairy = Dairy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dairy_params
      params.require(:dairy).permit(:id, :date, :milk)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dairies_helper.rb
module DairiesHelper
end

app/views/dairies/_form.html.erb
<%= form_with(model: dairy, local: true) do |form| %>
  <% if dairy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dairy.errors.count, "error") %> prohibited this dairy from being saved:</h2>

      <ul>
      <% dairy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, 'data-behaviour' => 'datepicker', id: :dairy_date, class: :datepicker %>
  </div>

  <div class="field">
    <%= form.label :milk %>
    <%= form.number_field :milk, id: :dairy_milk %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dairies/edit.html.erb
<h1>Editing Dairy</h1>

<%= render 'form', dairy: @dairy %>

<%= link_to 'Show', @dairy %> |
<%= link_to 'Back', dairies_path %>

app/views/dairies/home.html.erb
<h1>Welcome to Dairy Farm</h1>
<h3> where you can keep track of your produce</h3>

app/views/dairies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dairies</h1>



    <% @dairies.each do |dairy| %>
        Date:<p><%= dairy.date %></p>
        Milk:<p><%= dairy.milk %></p>
        <p><%= link_to 'Edit', edit_dairy_path(dairy) %> | <%= link_to 'Destroy', dairy, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<div id="container" style="width:100%; height:400px;"></div>

<script>
Highcharts.chart('container', {
  chart: {
      type: 'line'
  },

    title: {
        text: 'My Dairy Farm'
    },

    yAxis: {
        title: {
            text: 'Date of milking'
        }
    },
    legend: {
        layout: 'vertical',
        align: 'right',
        verticalAlign: 'middle'
    },

    plotOptions: {
        series: {
            label: {
                connectorAllowed: false
            },
            pointStart: 1
        }
    },

    series: [{
        name: 'Milk in litres',
        data: [<% @dairies.each do |dairy| %>
                 <%= dairy.milk %>,
               <% end %>]
    }],

    responsive: {
        rules: [{
            condition: {
                maxWidth: 500
            },
            chartOptions: {
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    verticalAlign: 'bottom'
                }
            }
        }]
    }

});
</script>

app/views/dairies/new.html.erb
<h1>New Dairy</h1>

<%= render 'form', dairy: @dairy %>

<%= link_to 'Back', dairies_path %>

app/views/dairies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @dairy.date %>
</p>

<p>
  <strong>Milk:</strong>
  <%= @dairy.milk %>
</p>

<%= link_to 'Edit', edit_dairy_path(@dairy) %> |
<%= link_to 'Back', dairies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DairyFarm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.highcharts.com/highcharts.js"></script>
  </head>

  <body>
    <div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-nav" aria-hidden="">
      <span class="sr-only">Toggle navigation</span>
      <span class="glyphicon glyphicon-menu-hamburger">
        <span></button>
        <a class="navbar-brand page-scroll" href="/"><p class="logo">Dairy</p></a>
      </div>
      <!-- navbar-header -->
      <div id="menu-nav" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to 'New Dairy', new_dairy_path %>
          </li>
          <li>
            <%= link_to 'Check Produce', dairies_path%>
          </li>
          <%if current_user %>
          <li>
            <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
          </li>
          <%else%>
          <li>
            <%= link_to 'Log In', new_user_session_path %>
          </li>
          <li>
            <%= link_to 'Sign Up', new_user_registration_path %>
          </li>
          <%end%>
        </ul>
      </div>
      <!-- navbar-collapse -->
    </div>
    <!-- container-fluid -->
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>